name: CD Pipeline
on:
  push:
    branches: ["main"]
jobs:
  call-ci-workflow:
    uses: ./.github/workflows/ci.yml

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/spring-docker:latest .
          docker push ${{secrets.DOCKERHUB_USERNAME}}/spring-docker:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Install SSH client
#         run: sudo apt-get install -y openssh-client

#       - name: Add SSH key
#         uses: shimataro/ssh-key-action@v2
#         with:
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           known_hosts: ${{ secrets.GCP_VM_IP }}

#       - name: Deploy to Google Cloud VM
#         run: |
#           ssh -o StrictHostKeyChecking=no username@${{ secrets.GCP_VM_IP }} << 'EOF'
#           docker pull your-dockerhub-username/your-app-name:latest
#           docker stop your-container-name || true
#           docker rm your-container-name || true
#           docker run -d --name your-container-name -p 3000:3000 your-dockerhub-username/your-app-name:latest
#           EOF
